# Generated by Django 5.1.1 on 2024-09-30 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=256, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField(max_length=2048)),
                ('abbreviation', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('name', models.CharField(max_length=256, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField(max_length=1024)),
                ('date_created', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('abstract', models.TextField(max_length=8096)),
                ('submitted', models.DateField()),
                ('url', models.TextField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.category')),
                ('written_by', models.ManyToManyField(to='main.author')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='writed_papers',
            field=models.ManyToManyField(to='main.paper'),
        ),
        migrations.AddField(
            model_name='category',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subject'),
        ),
    ]
