# Generated by Django 5.1.1 on 2024-10-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paper',
            name='summarization',
            field=models.TextField(max_length=16192, null=True),
        ),
    ]
